#!/usr/bin/env python3
"""
Bob Template Generator
Auto-generates deployment files from app.py and .env configuration
"""

import os
import re
import ast
from pathlib import Path
from typing import Dict, Set, List


class TemplateGenerator:
    def __init__(self, config_file: str = ".env"):
        self.config_file = config_file
        self.config = {}
        self.templates_dir = Path(__file__).parent / "templates"
        self.output_dir = Path.cwd()
        
    def load_config(self):
        """Load configuration from .env file"""
        if not os.path.exists(self.config_file):
            raise FileNotFoundError(
                f"{self.config_file} not found! "
                f"Copy .env.example to .env and fill in your values."
            )
        
        print(f"📖 Loading configuration from {self.config_file}...")
        
        with open(self.config_file, 'r') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    self.config[key.strip()] = value.strip()
        
        # Validate required fields
        required_fields = [
            'APP_NAME', 'APP_PORT', 'REPLICAS', 'GITHUB_REPO',
            'GITHUB_BRANCH', 'OPENSHIFT_NAMESPACE', 'OPENSHIFT_CLUSTER',
            'PYTHON_VERSION', 'HEALTH_CHECK_PATH'
        ]
        
        missing = [f for f in required_fields if f not in self.config]
        if missing:
            raise ValueError(f"Missing required fields in .env: {', '.join(missing)}")
        
        print(f"✓ Configuration loaded successfully")
        print(f"  App Name: {self.config['APP_NAME']}")
        print(f"  Namespace: {self.config['OPENSHIFT_NAMESPACE']}")
        print(f"  GitHub: {self.config['GITHUB_REPO']}")
        
    def detect_dependencies(self, app_file: str = "app.py") -> Set[str]:
        """Auto-detect Python dependencies from app.py"""
        if not os.path.exists(app_file):
            raise FileNotFoundError(f"{app_file} not found!")
        
        print(f"\n🔍 Analyzing {app_file} for dependencies...")
        
        dependencies = set()
        
        with open(app_file, 'r') as f:
            content = f.read()
        
        try:
            tree = ast.parse(content)
            
            for node in ast.walk(tree):
                if isinstance(node, ast.Import):
                    for alias in node.names:
                        dependencies.add(alias.name.split('.')[0])
                elif isinstance(node, ast.ImportFrom):
                    if node.module:
                        dependencies.add(node.module.split('.')[0])
        except SyntaxError as e:
            print(f"⚠️  Warning: Could not parse {app_file}: {e}")
            print("   You may need to manually create requirements.txt")
        
        # Filter out standard library modules
        stdlib_modules = {
            'os', 'sys', 'json', 'time', 'datetime', 'random', 're',
            'math', 'collections', 'itertools', 'functools', 'typing',
            'pathlib', 'logging', 'argparse', 'subprocess', 'threading',
            'multiprocessing', 'asyncio', 'unittest', 'io', 'csv'
        }
        
        external_deps = dependencies - stdlib_modules
        
        # Map common imports to package names
        package_mapping = {
            'flask': 'Flask==3.0.0',
            'requests': 'requests==2.31.0',
            'numpy': 'numpy==1.26.0',
            'pandas': 'pandas==2.1.0',
            'sqlalchemy': 'SQLAlchemy==2.0.0',
            'psycopg2': 'psycopg2-binary==2.9.9',
            'redis': 'redis==5.0.0',
            'celery': 'celery==5.3.0',
            'fastapi': 'fastapi==0.104.0',
            'pydantic': 'pydantic==2.5.0',
            'jwt': 'PyJWT==2.8.0',
            'bcrypt': 'bcrypt==4.1.0',
        }
        
        packages = []
        for dep in sorted(external_deps):
            if dep in package_mapping:
                packages.append(package_mapping[dep])
            else:
                packages.append(dep)
        
        print(f"✓ Found {len(packages)} external dependencies:")
        for pkg in packages:
            print(f"  - {pkg}")
        
        return packages
    
    def generate_requirements_txt(self, dependencies: Set[str]):
        """Generate requirements.txt file"""
        output_file = self.output_dir / "requirements.txt"
        
        print(f"\n📝 Generating {output_file}...")
        
        with open(output_file, 'w') as f:
            f.write("# Auto-generated by Bob Template Generator\n")
            f.write("# Add any additional dependencies below\n\n")
            for dep in sorted(dependencies):
                f.write(f"{dep}\n")
        
        print(f"✓ Created {output_file}")
    
    def render_template(self, template_path: Path) -> str:
        """Render a template file with config values"""
        with open(template_path, 'r') as f:
            content = f.read()
        
        # Replace {{VAR}} with config values
        for key, value in self.config.items():
            content = content.replace(f"{{{{{key}}}}}", value)
        
        return content
    
    def generate_file(self, template_name: str, output_name: str = None):
        """Generate a file from template"""
        if output_name is None:
            output_name = template_name.replace('.template', '')
        
        template_path = self.templates_dir / template_name
        
        if not template_path.exists():
            print(f"⚠️  Template not found: {template_path}")
            return
        
        # Handle k8s subdirectory
        if 'k8s/' in template_name:
            output_dir = self.output_dir / "k8s"
            output_dir.mkdir(exist_ok=True)
            output_file = output_dir / output_name.replace('k8s/', '')
        else:
            output_file = self.output_dir / output_name
        
        print(f"📝 Generating {output_file}...")
        
        content = self.render_template(template_path)
        
        with open(output_file, 'w') as f:
            f.write(content)
        
        print(f"✓ Created {output_file}")
    
    def generate_all(self):
        """Generate all deployment files"""
        print("\n" + "="*60)
        print("🚀 Bob Template Generator")
        print("="*60)
        
        # Load configuration
        self.load_config()
        
        # Detect dependencies
        dependencies = self.detect_dependencies()
        
        # Generate requirements.txt
        self.generate_requirements_txt(dependencies)
        
        # Generate all template files
        print("\n📦 Generating deployment files...")
        
        templates = [
            ('Dockerfile.template', 'Dockerfile'),
            ('Jenkinsfile.template', 'Jenkinsfile'),
            ('buildconfig.yaml.template', 'buildconfig.yaml'),
            ('k8s/deployment.yaml.template', 'k8s/deployment.yaml'),
            ('k8s/service.yaml.template', 'k8s/service.yaml'),
            ('k8s/route.yaml.template', 'k8s/route.yaml'),
        ]
        
        for template_name, output_name in templates:
            self.generate_file(template_name, output_name)
        
        print("\n" + "="*60)
        print("✅ All files generated successfully!")
        print("="*60)
        
        self.print_next_steps()
    
    def print_next_steps(self):
        """Print next steps for the user"""
        app_name = self.config['APP_NAME']
        namespace = self.config['OPENSHIFT_NAMESPACE']
        github_repo = self.config['GITHUB_REPO']
        
        print("\n📋 Next Steps:")
        print("\n1. Review the generated files:")
        print("   - Dockerfile")
        print("   - Jenkinsfile")
        print("   - buildconfig.yaml")
        print("   - k8s/deployment.yaml")
        print("   - k8s/service.yaml")
        print("   - k8s/route.yaml")
        print("   - requirements.txt")
        
        print("\n2. Push to GitHub:")
        print(f"   git add .")
        print(f"   git commit -m 'Add deployment configuration'")
        print(f"   git push origin main")
        
        print("\n3. Apply BuildConfig to OpenShift:")
        print(f"   oc apply -f buildconfig.yaml")
        
        print("\n4. Trigger deployment via Bob:")
        print(f"   curl -k -X POST https://bob-orchestrator-{namespace}.apps.your-cluster.com/webhook \\")
        print(f"     -H 'Content-Type: application/json' \\")
        print(f"     -d '{{\"text\": \"/pipeline {app_name}-pipeline {namespace}\"}}'")
        
        print("\n5. Monitor deployment:")
        print(f"   oc get builds -n {namespace} -w")
        print(f"   oc get pods -l app={app_name} -n {namespace}")
        
        print("\n6. Access your application:")
        print(f"   oc get route {app_name} -n {namespace}")
        
        print("\n" + "="*60)
        print("🎉 Happy Deploying!")
        print("="*60 + "\n")


def main():
    try:
        generator = TemplateGenerator()
        generator.generate_all()
    except Exception as e:
        print(f"\n❌ Error: {e}")
        print("\nPlease ensure:")
        print("1. You have copied .env.example to .env")
        print("2. You have filled in all required values in .env")
        print("3. You have an app.py file in the current directory")
        exit(1)


if __name__ == "__main__":
    main()

# Made with Bob
